[workspace]
members = ["./core", "./ui", "./server", "./data", "./db", "./cli"]

[tasks.default]
dependencies = ["doc"]

[tasks.doc]
command = "cargo"
args = ["doc", "--workspace", "--no-deps", "--document-private-items"]
